// 'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
// import {Footer} from "@/components/sections/Footer";
// import Navbar from "@/components/Navbar";
// import dynamic from 'next/dynamic'

// const ClientClerkProvider = dynamic(() => import('@/hooks/providers'), { ssr: false });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Luxuria ai" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden antialiased scroll-smooth`}
        >
       
          {children}
         
      </body>
    </html>
  );
}
